### ISSUE TITLE
Problem to match consumer signature

### ISSUE THREAD

**Issue by cgnunezbantics** [scudai/woocommerce-api-java#1]
Hello, we testing your code. We have problems to match the consumer signature.
In:  woocommerce-api-java/src/main/java/technology/onebyte/woocommerce/WooCommerceConnector.java
In line 189: We add a ampersand simbol to the string to match with sign woocommerce

byte[] keyBytes = (this.consumerSecret+"&").getBytes(ENC);

Is working for us.
Thanks

**Comment by scudai** [comment]
Hi, 

thanks for report. Can you please tell me which version of WooCommerce have you used? I am testing with 2.3.13 and when I make change as you suggested I am getting error from WooCommerce API: 

{"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}

Why do you actually add '&' symbol to consumer secret? Consumer secret should be same as is in  Wordpress Admin panel > Users > UserXYZ > WooCommerce API Keys. UserXYZ = 'User who will be used to communicate with WooCommerce API'

**Comment by cgnunezbantics** [comment]
HI, 
The Version of woocommerce that we are using is 2.4.6 with version 3 de api REST of woocommerce.
Debuging php code (we made out in text file on server a log) from this source:
/wp-content/plugins/woocommerce/includes/api/class-wc-api-authentication.php
we can see the customer secret var + '&' has coded with hmac-sha1 function.
we don't if is correct or bug of woocommerce, but works.
* Other problem in the url send, http://uuuu.com on http://www.uuuu.com

**Comment by scudai** [comment]
Thank you for detail description. You were right, I have not realized that API version v3 was released. So I have decided to update code as you suggested. I also made my first release of the library. In the moment I will support only API v3 since WooCommerce also mentioned in documentation that v1 and v2 will be removed in future.

**Comment by scudai** [comment]
Closing the issue, FIXED.
